version: '3.1'

services:
  api:
    container_name: websocket-maven
    image: websocket-maven:0.1
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - /etc/localtime:/etc/localtime
